---
- name: Disable SELinux
  shell: sed -i '/SELINUX=enforcing/s/enforcing/disabled/' /etc/selinux/config
  ignore_errors: True
- name: Temporary Disable SElinux
  shell: setenforce 0
  ignore_errors: True
- name: Disable Firewalld
  service:
    name: firewalld
    state: stopped
    enabled: no
