- name: Create the mongos server configuration file
  template:
    src: mongos/mongos.conf.j2
    dest: "{{ var_conf_path }}/mongos.conf"
  
- name: Start mongod mongos server
  shell: "{{ var_workerpath }}/bin/mongos  -f {{ var_conf_path }}/mongos.conf"

- wait_for:
    port: "{{ var_configs_port }}"
    delay: 3

- name: Create the file to initialize the mongos replica set
  template:
    src: mongos/mongos_init.js.j2
    dest: /tmp/mongos_init.js

- name: Initialize the replication set
  shell:  "{{ var_workerpath }}/bin/mongo localhost:{{ var_mongos_port }}/admin /tmp/mongos_init.js"
  run_once: true
  delegate_to: "{{ groups['mongod'][0] }}"

- name: Delete initialize file
  file:
    path: /tmp/mongos_init.js
    state: absent
