- name: Create the shard3 server configuration file
  template:
    src: shard3/shard3.conf.j2
    dest: "{{ var_conf_path }}/shard3.conf"
  
- name: Start mongod shard3 server
  shell: "{{ var_workerpath }}/bin/mongod -f {{ var_conf_path }}/shard3.conf"

- wait_for:
    port: "{{ var_configs_port }}"
    delay: 3

- name: Create the file to initialize the shard3 replica set
  template:
    src: shard3/shard3_init.js.j2
    dest: /tmp/shard3_init.js

- name: Initialize the replication set
  shell:  "{{ var_workerpath }}/bin/mongo localhost:{{ var_shard3_port }}/admin /tmp/shard3_init.js"
  run_once: true
  delegate_to: "{{ groups['mongod'][2] }}"

- name: Delete initialize file
  file:
    path: /tmp/shard3_init.js
    state: absent
