- name: Create the shard1 server configuration file
  template:
    src: shard1/shard1.conf.j2
    dest: "{{ var_conf_path }}/shard1.conf"
  
- name: Start mongod shard1 server
  shell: "{{ var_workerpath }}/bin/mongod  -f {{ var_conf_path }}/shard1.conf"

- wait_for:
    port: "{{ var_configs_port }}"
    delay: 3

- name: Create the file to initialize the shard1 replica set
  template:
    src: shard1/shard1_init.js.j2
    dest: /tmp/shard1_init.js

- name: Initialize the replication set
  shell:  "{{ var_workerpath }}/bin/mongo localhost:{{ var_shard1_port }}/admin /tmp/shard1_init.js"
  run_once: true
  delegate_to: "{{ groups['mongod'][0] }}"

- name: Delete initialize file
  file:
    path: /tmp/shard1_init.js
    state: absent
