- name: update config
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf
  notify: restart nginx
- name: create directory
  file:
    name: /etc/nginx/conf.d/tcp
    state: directory
    mode: 0755
    owner: nginx
    group: nginx
- name: add mysql proxy
  template: src=mysql.conf.j2 dest=/etc/nginx/conf.d/tcp/mysql.conf
