---
- include: create_group.yml
- include: create_user.yml
- include: install_nginx.yml
- include: update_index.yml
- include: copy_config.yml
  notify: restart nginx
- include: service.yml
- name: delete conf.d/*.conf
  file:
    name: /etc/nginx/conf.d/default.conf
    state: absent
  notify: restart nginx
